version: "3"
services:
        bot:
                build:
                        context: .
                        dockerfile: Dockerfile
                image: apppalestrebot
                container_name: bot
                restart: always
                tty: true
                volumes:
                        - "./data:/app/data"

